target-version = "py312"
line-length = 79
extend-exclude = [
    "migrations",
    "settings.py",
]

[lint]
select = ["E", "F", "W", "I", "Q"]

[lint.flake8-quotes]
inline-quotes = "single"
multiline-quotes = "single"
